app = "my-app1"
primary_region = "sea"

[build]
  builder = "paketo/buildpacks:base"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true